0|Catppuccin-Mocha|~/.config/swww/Catppuccin-Mocha/switch_swirl.jpg
0|Catppuccin-Latte|~/.config/swww/Catppuccin-Latte/abstract_blured.jpg
0|Decay-Green|~/.config/swww/Decay-Green/arcade_decay_red.png
0|Rose-Pine|~/.config/swww/Rose-Pine/mountain_dragon_pink.jpg
0|Tokyo-Night|~/.config/swww/Tokyo-Night/lowpoly_street.png
0|Material-Sakura|~/.config/swww/Material-Sakura/material_pastel_4.jpg
1|Graphite-Mono|~/.config/swww/Graphite-Mono/lain-cap.jpg
0|Cyberpunk-Edge|~/.config/swww/Cyberpunk-Edge/cyberpunk_dave.png
0|Frosted-Glass|~/.config/swww/Frosted-Glass/teal_mountain.png
